-- ============================================================
-- EduCode — Baza kontenti tarjimalari: DARS O'YINLARI KONTENTI (JSON)
--   12 ta interaktiv o'yin kontenti (savollar, variantlar, juftliklar, taxta) -> ru, en, kaa
--
-- 42_kontent_tarjimalari.sql dan KEYIN ishga tushiring.
-- Qayta ishga tushirish xavfsiz (ON CONFLICT DO UPDATE).
-- ============================================================

DO $$
BEGIN
  -- [sintaksis-poygasi]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"questions":[{"text":"Как в Python выделяются блоки кода?","seconds":20,"options":[{"text":"Отступами","correct":true},{"text":"Фигурными скобками","correct":false},{"text":"Точкой с запятой","correct":false},{"text":"begin и end","correct":false}]},{"text":"Какой тип значения возвращает функция input()?","seconds":20,"options":[{"text":"Строка (str)","correct":true},{"text":"Целое число (int)","correct":false},{"text":"Вещественное число (float)","correct":false},{"text":"Логическое (bool)","correct":false}]},{"text":"Что выведет print(\"5\" + \"3\")?","seconds":20,"options":[{"text":"53","correct":true},{"text":"8","correct":false},{"text":"5 3","correct":false},{"text":"Ошибка","correct":false}]},{"text":"Что выведет print(\"a\",\"b\",sep=\"-\")?","seconds":20,"options":[{"text":"a-b","correct":true},{"text":"a b","correct":false},{"text":"ab","correct":false},{"text":"a - b","correct":false}]},{"text":"Сколько пробелов рекомендуется для одного уровня отступа?","seconds":15,"options":[{"text":"4","correct":true},{"text":"1","correct":false},{"text":"2","correct":false},{"text":"8","correct":false}]},{"text":"Какое имя файла написано правильно?","seconds":20,"options":[{"text":"first_prog.py","correct":true},{"text":"1prog.py","correct":false},{"text":"my program.py","correct":false},{"text":"prog.txt","correct":false}]},{"text":"Для чего используется параметр end в функции print()?","seconds":20,"options":[{"text":"Определяет символ окончания строки","correct":true},{"text":"Завершает программу","correct":false},{"text":"Останавливает цикл","correct":false},{"text":"Закрывает файл","correct":false}]},{"text":"Какая ошибка возникнет при нарушении структуры отступов?","seconds":20,"options":[{"text":"IndentationError","correct":true},{"text":"NameError","correct":false},{"text":"TypeError","correct":false},{"text":"ValueError","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'sintaksis-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"questions":[{"text":"How are code blocks structured and delimited in Python?","seconds":20,"options":[{"text":"Indentation (whitespace)","correct":true},{"text":"Curly braces {}","correct":false},{"text":"Semicolons ;","correct":false},{"text":"begin/end keywords","correct":false}]},{"text":"What data type does the built-in input() function return?","seconds":20,"options":[{"text":"String (str)","correct":true},{"text":"Integer (int)","correct":false},{"text":"Float (float)","correct":false},{"text":"Boolean (bool)","correct":false}]},{"text":"What is the output of print(\"5\" + \"3\")?","seconds":20,"options":[{"text":"53","correct":true},{"text":"8","correct":false},{"text":"5 3","correct":false},{"text":"TypeError","correct":false}]},{"text":"What is the output of print(\"a\",\"b\",sep=\"-\")?","seconds":20,"options":[{"text":"a-b","correct":true},{"text":"a b","correct":false},{"text":"ab","correct":false},{"text":"a - b","correct":false}]},{"text":"How many spaces per indentation level does PEP 8 recommend?","seconds":15,"options":[{"text":"4 spaces","correct":true},{"text":"1 space","correct":false},{"text":"2 spaces","correct":false},{"text":"8 spaces","correct":false}]},{"text":"Which filename adheres to standard Python naming conventions?","seconds":20,"options":[{"text":"first_prog.py","correct":true},{"text":"1prog.py","correct":false},{"text":"my program.py","correct":false},{"text":"prog.txt","correct":false}]},{"text":"What is the purpose of the end parameter in print()?","seconds":20,"options":[{"text":"Specifies string appended at the end","correct":true},{"text":"Terminates script","correct":false},{"text":"Breaks loop","correct":false},{"text":"Closes file stream","correct":false}]},{"text":"Which exception is raised when indentation is inconsistent?","seconds":20,"options":[{"text":"IndentationError","correct":true},{"text":"NameError","correct":false},{"text":"TypeError","correct":false},{"text":"ValueError","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'sintaksis-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"questions":[{"text":"Pythonda kod blokları ne arqalı ajıratıladı?","seconds":20,"options":[{"text":"Sheginiw (indent)","correct":true},{"text":"Figuralı qawıs {}","correct":false},{"text":"Útirli noqat ;","correct":false},{"text":"begin hám end","correct":false}]},{"text":"input() qanday túrdegi mánis qaytaradı?","seconds":20,"options":[{"text":"Tekst (str)","correct":true},{"text":"Pútin san (int)","correct":false},{"text":"Bólshik san (float)","correct":false},{"text":"Logikalıq mánis (bool)","correct":false}]},{"text":"print(\"5\" + \"3\") ne shıǵaradı?","seconds":20,"options":[{"text":"53","correct":true},{"text":"8","correct":false},{"text":"5 3","correct":false},{"text":"Qátelik","correct":false}]},{"text":"print(\"a\",\"b\",sep=\"-\") ne shıǵaradı?","seconds":20,"options":[{"text":"a-b","correct":true},{"text":"a b","correct":false},{"text":"ab","correct":false},{"text":"a - b","correct":false}]},{"text":"Sheginiw ushın neshe bos orın usınıs etiledi?","seconds":15,"options":[{"text":"4","correct":true},{"text":"1","correct":false},{"text":"2","correct":false},{"text":"8","correct":false}]},{"text":"Qaysı fayl atı durıs jazılǵan?","seconds":20,"options":[{"text":"birinshi_dastur.py","correct":true},{"text":"1dastur.py","correct":false},{"text":"mening dasturim.py","correct":false},{"text":"dastur.txt","correct":false}]},{"text":"end parametri ne ushın kerek?","seconds":20,"options":[{"text":"print() aqırına ne qosılıwın belgileydi","correct":true},{"text":"Dastúrdi toqtatadı","correct":false},{"text":"Cikl qádemin úzedi","correct":false},{"text":"Fayldı jabıw","correct":false}]},{"text":"Sheginiw nadurıs bolsa qanday qátelik shıǵadı?","seconds":20,"options":[{"text":"IndentationError","correct":true},{"text":"NameError","correct":false},{"text":"TypeError","correct":false},{"text":"ValueError","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'sintaksis-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [royxatlar-sikllar-poygasi]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"questions":[{"text":"Что вернет list(range(2, 6))?","seconds":25,"options":[{"text":"[2, 3, 4, 5]","correct":true},{"text":"[2, 3, 4, 5, 6]","correct":false},{"text":"[3, 4, 5]","correct":false},{"text":"[2, 6]","correct":false}]},{"text":"Какой метод добавляет элемент в конец списка?","seconds":20,"options":[{"text":"append()","correct":true},{"text":"add()","correct":false},{"text":"push()","correct":false},{"text":"insert_last()","correct":false}]},{"text":"Сколько раз выполнится цикл for i in range(1, 10, 2)?","seconds":25,"options":[{"text":"5 раз","correct":true},{"text":"9 раз","correct":false},{"text":"10 раз","correct":false},{"text":"4 раза","correct":false}]},{"text":"Что возвращает len([10, 20, [30, 40]])?","seconds":20,"options":[{"text":"3","correct":true},{"text":"4","correct":false},{"text":"2","correct":false},{"text":"Ошибка","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'royxatlar-sikllar-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"questions":[{"text":"What is returned by list(range(2, 6))?","seconds":25,"options":[{"text":"[2, 3, 4, 5]","correct":true},{"text":"[2, 3, 4, 5, 6]","correct":false},{"text":"[3, 4, 5]","correct":false},{"text":"[2, 6]","correct":false}]},{"text":"Which method appends an element to the end of a list?","seconds":20,"options":[{"text":"append()","correct":true},{"text":"add()","correct":false},{"text":"push()","correct":false},{"text":"insert_last()","correct":false}]},{"text":"How many iterations will for i in range(1, 10, 2) run?","seconds":25,"options":[{"text":"5 times","correct":true},{"text":"9 times","correct":false},{"text":"10 times","correct":false},{"text":"4 times","correct":false}]},{"text":"What is the return value of len([10, 20, [30, 40]])?","seconds":20,"options":[{"text":"3","correct":true},{"text":"4","correct":false},{"text":"2","correct":false},{"text":"TypeError","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'royxatlar-sikllar-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"questions":[{"text":"list(range(2, 6)) ne qaytaradı?","seconds":25,"options":[{"text":"[2, 3, 4, 5]","correct":true},{"text":"[2, 3, 4, 5, 6]","correct":false},{"text":"[3, 4, 5]","correct":false},{"text":"[2, 6]","correct":false}]},{"text":"Dizim aqırına element qosıwshı metod qaysı?","seconds":20,"options":[{"text":"append()","correct":true},{"text":"add()","correct":false},{"text":"push()","correct":false},{"text":"insert_last()","correct":false}]},{"text":"for i in range(1, 10, 2) cikli neshe márte aylanadı?","seconds":25,"options":[{"text":"5 márte","correct":true},{"text":"9 márte","correct":false},{"text":"10 márte","correct":false},{"text":"4 márte","correct":false}]},{"text":"len([10, 20, [30, 40]]) natiyjesi nege teń?","seconds":20,"options":[{"text":"3","correct":true},{"text":"4","correct":false},{"text":"2","correct":false},{"text":"Qátelik","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'royxatlar-sikllar-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [shartlar-poygasi]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"questions":[{"text":"Чему равно выражение: not (5 > 3 and 2 < 4)?","seconds":20,"options":[{"text":"False","correct":true},{"text":"True","correct":false},{"text":"None","correct":false},{"text":"Ошибка","correct":false}]},{"text":"Какое ключевое слово обозначает ''иначе если'' в Python?","seconds":15,"options":[{"text":"elif","correct":true},{"text":"else if","correct":false},{"text":"elseif","correct":false},{"text":"when","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'shartlar-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"questions":[{"text":"What is the boolean evaluation of: not (5 > 3 and 2 < 4)?","seconds":20,"options":[{"text":"False","correct":true},{"text":"True","correct":false},{"text":"None","correct":false},{"text":"SyntaxError","correct":false}]},{"text":"Which keyword represents ''else if'' chaining in Python?","seconds":15,"options":[{"text":"elif","correct":true},{"text":"else if","correct":false},{"text":"elseif","correct":false},{"text":"when","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'shartlar-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"questions":[{"text":"not (5 > 3 and 2 < 4) ańlatpasınıń nátiyjesi nege teń?","seconds":20,"options":[{"text":"False","correct":true},{"text":"True","correct":false},{"text":"None","correct":false},{"text":"Qátelik","correct":false}]},{"text":"Pythonda ''eger bolmasa'' (else if) mánisin qaysı gilt sóz bildiredi?","seconds":15,"options":[{"text":"elif","correct":true},{"text":"else if","correct":false},{"text":"elseif","correct":false},{"text":"when","correct":false}]}]}'::jsonb FROM lesson_games WHERE slug = 'shartlar-poygasi'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [modullar-va-funksiyalari]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"pairs":[{"left":"math.sqrt(x)","right":"Квадратный корень из числа"},{"left":"random.randint(a, b)","right":"Случайное целое число от a до b"},{"left":"time.sleep(s)","right":"Приостановка выполнения на s секунд"},{"left":"os.getcwd()","right":"Путь к текущей рабочей директории"},{"left":"sys.exit()","right":"Завершение работы программы"}]}'::jsonb FROM lesson_games WHERE slug = 'modullar-va-funksiyalari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"pairs":[{"left":"math.sqrt(x)","right":"Square root of x"},{"left":"random.randint(a, b)","right":"Random integer between a and b inclusive"},{"left":"time.sleep(s)","right":"Pause program execution for s seconds"},{"left":"os.getcwd()","right":"Get current working directory path"},{"left":"sys.exit()","right":"Terminate program execution"}]}'::jsonb FROM lesson_games WHERE slug = 'modullar-va-funksiyalari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"pairs":[{"left":"math.sqrt(x)","right":"Sanniń kvadrat tamırı"},{"left":"random.randint(a, b)","right":"a dan b ǵa shekemgi tosınnan pútin san"},{"left":"time.sleep(s)","right":"Dastúrdi s sekundqa toqtatıp turıw"},{"left":"os.getcwd()","right":"Házirgi islep turǵan papka jolin alıw"},{"left":"sys.exit()","right":"Dastúr jumısın juwmaqlaw"}]}'::jsonb FROM lesson_games WHERE slug = 'modullar-va-funksiyalari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [xatolar-va-sabablari]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"pairs":[{"left":"IndexError","right":"Обращение к несуществующему индексу списка"},{"left":"KeyError","right":"Обращение к несуществующему ключу словаря"},{"left":"TypeError","right":"Несовместимые типы данных в операции (''5'' + 2)"},{"left":"ValueError","right":"Некорректное значение для преобразования: int(''abc'')"},{"left":"ZeroDivisionError","right":"Деление числа на ноль"}]}'::jsonb FROM lesson_games WHERE slug = 'xatolar-va-sabablari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"pairs":[{"left":"IndexError","right":"Accessing out-of-range index in a list"},{"left":"KeyError","right":"Querying a non-existent key in dictionary"},{"left":"TypeError","right":"Operating on incompatible data types (''5'' + 2)"},{"left":"ValueError","right":"Invalid literal for numeric conversion: int(''abc'')"},{"left":"ZeroDivisionError","right":"Attempting division by zero"}]}'::jsonb FROM lesson_games WHERE slug = 'xatolar-va-sabablari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"pairs":[{"left":"IndexError","right":"Dizim indeksinen tıs elementke múrájat etiw"},{"left":"KeyError","right":"Sózlikte joq giltke múrájat etiw"},{"left":"TypeError","right":"Sáykes kelmeytuǵın maǵlıwmat túrleri boyınsha amal (''5'' + 2)"},{"left":"ValueError","right":"Sanǵa aylandırıwǵa bolmaytuǵın qáte mánis: int(''abc'')"},{"left":"ZeroDivisionError","right":"Sandı nolge bóliw"}]}'::jsonb FROM lesson_games WHERE slug = 'xatolar-va-sabablari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [amallar-va-natijalari]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"pairs":[{"left":"17 // 5","right":"3 (целочисленное деление)"},{"left":"17 % 5","right":"2 (остаток от деления)"},{"left":"2 ** 4","right":"16 (возведение в степень)"},{"left":"10 / 2","right":"5.0 (вещественное деление)"},{"left":"''a'' * 3","right":"''aaa'' (дублирование строки)"}]}'::jsonb FROM lesson_games WHERE slug = 'amallar-va-natijalari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"pairs":[{"left":"17 // 5","right":"3 (integer floor division)"},{"left":"17 % 5","right":"2 (modulo remainder)"},{"left":"2 ** 4","right":"16 (exponentiation power)"},{"left":"10 / 2","right":"5.0 (floating-point division)"},{"left":"''a'' * 3","right":"''aaa'' (string replication)"}]}'::jsonb FROM lesson_games WHERE slug = 'amallar-va-natijalari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"pairs":[{"left":"17 // 5","right":"3 (pútin bóliw)"},{"left":"17 % 5","right":"2 (qaldıq)"},{"left":"2 ** 4","right":"16 (dárejege kóteriw)"},{"left":"10 / 2","right":"5.0 (bólshikli bóliw)"},{"left":"''a'' * 3","right":"''aaa'' (tekstti kóbeytiw)"}]}'::jsonb FROM lesson_games WHERE slug = 'amallar-va-natijalari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [matn-metodlari]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"pairs":[{"left":"s.strip()","right":"Удаление пробелов по краям строки"},{"left":"s.split()","right":"Разбиение строки на список слов"},{"left":"'',''.join(arr)","right":"Объединение элементов списка в строку"},{"left":"s.replace(a, b)","right":"Замена подстроки a на b"},{"left":"s.lower()","right":"Преобразование символов к нижнему регистру"}]}'::jsonb FROM lesson_games WHERE slug = 'matn-metodlari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"pairs":[{"left":"s.strip()","right":"Remove leading and trailing whitespace"},{"left":"s.split()","right":"Split string into list of substrings"},{"left":"'',''.join(arr)","right":"Concatenate list elements with delimiter"},{"left":"s.replace(a, b)","right":"Substitute occurrences of a with b"},{"left":"s.lower()","right":"Convert all characters to lowercase"}]}'::jsonb FROM lesson_games WHERE slug = 'matn-metodlari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"pairs":[{"left":"s.strip()","right":"Qatardıń eki shetindegi bos orınlardı óshiriw"},{"left":"s.split()","right":"Tekstti sózler dizimine ajıratıw"},{"left":"'',''.join(arr)","right":"Dizim elementlerin ajıratıwshı menen biriktiriw"},{"left":"s.replace(a, b)","right":"Teksttegi a bólegin b ǵa almastırıw"},{"left":"s.lower()","right":"Barlıq háriplerdi kishi registrge ótkeriw"}]}'::jsonb FROM lesson_games WHERE slug = 'matn-metodlari'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [python-atamalari-krossvord]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"clues":[{"num":1,"dir":"across","clue":"Переменная, хранящая данные","answer":"VARIABLE"},{"num":2,"dir":"down","clue":"Функция вывода на экран в Python","answer":"PRINT"},{"num":3,"dir":"across","clue":"Тип данных для целых чисел","answer":"INTEGER"},{"num":4,"dir":"down","clue":"Структура для повторения действий","answer":"LOOP"}]}'::jsonb FROM lesson_games WHERE slug = 'python-atamalari-krossvord'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"clues":[{"num":1,"dir":"across","clue":"Named container for storing data values","answer":"VARIABLE"},{"num":2,"dir":"down","clue":"Standard console output function in Python","answer":"PRINT"},{"num":3,"dir":"across","clue":"Numeric data type representing whole numbers","answer":"INTEGER"},{"num":4,"dir":"down","clue":"Control structure for repeating statements","answer":"LOOP"}]}'::jsonb FROM lesson_games WHERE slug = 'python-atamalari-krossvord'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"clues":[{"num":1,"dir":"across","clue":"Mánisti saqlawshı atalǵan idıs","answer":"VARIABLE"},{"num":2,"dir":"down","clue":"Ekranǵa maǵlıwmat shıǵarıwshı funktsiya","answer":"PRINT"},{"num":3,"dir":"across","clue":"Pútin sanlar ushın maǵlıwmat túri","answer":"INTEGER"},{"num":4,"dir":"down","clue":"Amallardı qaytalawshı struktura","answer":"LOOP"}]}'::jsonb FROM lesson_games WHERE slug = 'python-atamalari-krossvord'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [sikllar-va-funksiyalar-krossvord]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"clues":[{"num":1,"dir":"across","clue":"Ключевое слово для объявления функции","answer":"DEF"},{"num":2,"dir":"down","clue":"Возврат значения из функции","answer":"RETURN"},{"num":3,"dir":"across","clue":"Цикл, выполняющийся пока условие истинно","answer":"WHILE"},{"num":4,"dir":"down","clue":"Прерывание выполнения текущего цикла","answer":"BREAK"}]}'::jsonb FROM lesson_games WHERE slug = 'sikllar-va-funksiyalar-krossvord'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"clues":[{"num":1,"dir":"across","clue":"Keyword used to define a custom function","answer":"DEF"},{"num":2,"dir":"down","clue":"Keyword to pass a result back from a function","answer":"RETURN"},{"num":3,"dir":"across","clue":"Loop that runs as long as a condition evaluates to True","answer":"WHILE"},{"num":4,"dir":"down","clue":"Statement that immediately exits the enclosing loop","answer":"BREAK"}]}'::jsonb FROM lesson_games WHERE slug = 'sikllar-va-funksiyalar-krossvord'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"clues":[{"num":1,"dir":"across","clue":"Funktsiya jaratıw ushın gilt sóz","answer":"DEF"},{"num":2,"dir":"down","clue":"Funktsiyadan nátiyjeni qaytarıw","answer":"RETURN"},{"num":3,"dir":"across","clue":"Shárt True bolǵansha aylanatuǵın cikl","answer":"WHILE"},{"num":4,"dir":"down","clue":"Cikl jumısın múddetinen aldın toqtatıw","answer":"BREAK"}]}'::jsonb FROM lesson_games WHERE slug = 'sikllar-va-funksiyalar-krossvord'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [dasturlash-asoslari-jeopardy-1]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"categories":[{"name":"Синтаксис","clues":[{"value":100,"question":"Символ начала комментария в Python","answer":"#"},{"value":200,"question":"Как в Python обозначается равенство при проверке?","answer":"=="}]},{"name":"Типы данных","clues":[{"value":100,"question":"Какой тип имеет значение True?","answer":"bool"},{"value":200,"question":"Неизменяемый аналог списка","answer":"tuple (кортеж)"}]},{"name":"Списки","clues":[{"value":100,"question":"Индекс первого элемента списка","answer":"0"},{"value":200,"question":"Метод для удаления последнего элемента","answer":"pop()"}]}]}'::jsonb FROM lesson_games WHERE slug = 'dasturlash-asoslari-jeopardy-1'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"categories":[{"name":"Syntax","clues":[{"value":100,"question":"Single-line comment symbol in Python","answer":"#"},{"value":200,"question":"Equality comparison operator in Python","answer":"=="}]},{"name":"Data Types","clues":[{"value":100,"question":"What data type is True or False?","answer":"bool"},{"value":200,"question":"Immutable equivalent of a Python list","answer":"tuple"}]},{"name":"Lists","clues":[{"value":100,"question":"Zero-based index of the first list element","answer":"0"},{"value":200,"question":"Method that removes and returns the last element","answer":"pop()"}]}]}'::jsonb FROM lesson_games WHERE slug = 'dasturlash-asoslari-jeopardy-1'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"categories":[{"name":"Sintaksis","clues":[{"value":100,"question":"Pythonda kommentariy qaysı belgi menen baslanadı?","answer":"#"},{"value":200,"question":"Teńlikti tekseriw operatorı","answer":"=="}]},{"name":"Maǵlıwmat túrleri","clues":[{"value":100,"question":"True mánisi qaysı túrge kiredi?","answer":"bool"},{"value":200,"question":"Dizimniń ózgermeytuǵın analogı","answer":"tuple"}]},{"name":"Dizimler","clues":[{"value":100,"question":"Dizimniń birinshi elementiniń indeksi","answer":"0"},{"value":200,"question":"Dizimniń sońǵı elementin óshirip alıwshı metod","answer":"pop()"}]}]}'::jsonb FROM lesson_games WHERE slug = 'dasturlash-asoslari-jeopardy-1'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

  -- [dasturlash-asoslari-jeopardy-2]
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'ru', 'content', '{"categories":[{"name":"Функции","clues":[{"value":100,"question":"Ключевое слово для объявления функции","answer":"def"},{"value":200,"question":"Анонимная функция в одну строку","answer":"lambda"}]},{"name":"Словари","clues":[{"value":100,"question":"Из каких пар состоят элементы словаря?","answer":"Ключ и значение (key-value)"},{"value":200,"question":"Метод для безопасного получения значения без KeyError","answer":"get()"}]},{"name":"Модули","clues":[{"value":100,"question":"Модуль для работы со случайными числами","answer":"random"},{"value":200,"question":"Модуль для математических вычислений","answer":"math"}]}]}'::jsonb FROM lesson_games WHERE slug = 'dasturlash-asoslari-jeopardy-2'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'en', 'content', '{"categories":[{"name":"Functions","clues":[{"value":100,"question":"Keyword to define a function","answer":"def"},{"value":200,"question":"Single-line anonymous function keyword","answer":"lambda"}]},{"name":"Dictionaries","clues":[{"value":100,"question":"What pairs compose dictionary items?","answer":"Key-Value pairs"},{"value":200,"question":"Method to fetch value safely without KeyError","answer":"get()"}]},{"name":"Modules","clues":[{"value":100,"question":"Standard module for generating pseudo-random numbers","answer":"random"},{"value":200,"question":"Standard module for mathematical constants and functions","answer":"math"}]}]}'::jsonb FROM lesson_games WHERE slug = 'dasturlash-asoslari-jeopardy-2'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;
  INSERT INTO content_translations (resource, row_id, locale, field, value_json)
  SELECT 'lesson_games', id, 'kaa', 'content', '{"categories":[{"name":"Funktsiyalar","clues":[{"value":100,"question":"Funktsiya jaratıw gilt sózi","answer":"def"},{"value":200,"question":"Bir qatorlı anonim funktsiya","answer":"lambda"}]},{"name":"Sózlikler","clues":[{"value":100,"question":"Sózlik elementleri qanday jup bolıp saqlanadı?","answer":"Gilt hám mánis (key-value)"},{"value":200,"question":"KeyError shıǵarmaw ushın qollanılatuǵın metod","answer":"get()"}]},{"name":"Moduller","clues":[{"value":100,"question":"Tosınnan sanlar menen islesiw moduli","answer":"random"},{"value":200,"question":"Matematikalıq ámeller moduli","answer":"math"}]}]}'::jsonb FROM lesson_games WHERE slug = 'dasturlash-asoslari-jeopardy-2'
  ON CONFLICT (resource, row_id, locale, field) DO UPDATE SET value_json = EXCLUDED.value_json;

END $$;
